### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [9b/chirp#10]
Hi, I want to design a new logo for the project completely free..

**Comment by 9b** [comment]
Is there anything specific you'd like from me to guide the design? The current logo I have is robbed from a Japanese character. Something similar would be nice, but I am open to feedback!

**Comment by Arslanshn** [comment]
https://drive.google.com/open?id=1xeSMInOvqAVbiieLXdM0HOmViFuyi-hB
I have prepared a study for you:)

**Comment by 9b** [comment]
Thank you. I'd like to preserve the bird icon for the application as it fits best with the name.
