### ISSUE TITLE
Adding/removing search terms via CLI not reflected in chirp webapp

### ISSUE THREAD

**Issue by jalewis** [9b/chirp#13]
I deleted a monitor via google-alerts CLI and added a new monitor via CLI, Chirp has not reflected the change.   I expected the deleted monitor to be removed from Chirp and the new monitor to be added.

**Comment by 9b** [comment]
The command line tool is presently not considered an API for chirp. See #14 for future updates and commits. Behind the scenes, chirp manages the monitors and derives other data that the Google Alerts abstraction does not include.
