### ISSUE TITLE
Authentication failures when flagged as a bot

### ISSUE THREAD

**Issue by 9b** [9b/chirp#15]
Google seems to eventually identify the scripted accounts and forces a captcha. There is no way to automate around this, though 2FA does appear to be a good solution, though not perfect. This is a major issue to keeping the functionality within Chirp going. While annoying, one can swap accounts and still retain access to existing monitors as the RSS feeds are public.

**Comment by 9b** [comment]
Tracking within the core. https://github.com/9b/google-alerts/issues/2

**Comment by jayjpatel9717** [comment]
**Authentication Failed! undefined**

Solution Please?

**Comment by 9b** [comment]
Have you updated to the latest version of Chirp and also updated `google-alerts` to version `0.1.6`?

**Comment by jayjpatel9717** [comment]
Yes, i totally remove **chirp/**  and uninstall and reinstall **google-alerts 0.1.6**, And use new **Docker** file to run **chip/**.

Also in **Docker** when i close a terminal, And run the command again, I have to create an account again.
