### ISSUE TITLE
Mongo forking warning

### ISSUE THREAD

**Issue by deadbits** [9b/chirp#16]
After starting Celery, this warning is given about Mongo being opened after a fork:
```
[2018-05-26 11:00:38,234: WARNING/ForkPoolWorker-8] /Users/adam/Research/projects/google-alerts-pipeline/chirp/venv3/lib/python3.6/site-packages/pymongo/topology.py:149: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
  "MongoClient opened before fork. Create MongoClient only "
```

I believe this is due to the celery processes and multiple Mongo instances being opened. You can usually get around this by checking if the PID is 0 and if yes connect to Mongo, if not re-use an existing connection since one will already be opened - though since you're using Flask-Mongo I'm not sure if this is something you can deal with on the Chirp side..

I took a quick glance through the code but couldn't find an obvious spot where this would be happening on your end but figured I'd let you know since it will just keep creating new Mongo connections whenever it's called

**Comment by 9b** [comment]
I've seen these before and have yet to run into any major issues due to it. I could likely solve this by placing a lock on the celery jobs. I think celery is forking out and causing the warning. What I may end up doing is updating the beat to not fork and just keep one worker.

**Comment by deadbits** [comment]
Sounds good. Just figured I'd bring it up in case. This isn't really a bug, just more of a tidying up if there get to be lots of connections to the Mongo server. Could only really see it becoming a problem if a lot of people were using the same Chirp instance and the server couldn't handle all the connections.

But yeah, the lock should work or you should be able to get around it by checking the PID before calling your PyMono connect call. Could probably even just disable the warning message too if it's not a big deal.
```
if os.getpid() == 0:
    conn = pymongo.MongoClient('localhost:27017')
else:
    conn = pymongo.MongoClient('localhost:27017', connect=False)
```

**Comment by lambasoft** [comment]
@deadbits Can you explain how your solution works? I tried it and it worked for me. I just don't get how a getpid can give a 0?

**Comment by deadbits** [comment]
I'm not entirely sure _how_ it works either, but if I had to guess I'd assume the parent Python process will be PID 0 and any subprocesses get other responses?

Although, it seems like it would be the opposite, like how forking usually works: if you are the child proc getting the pid will return 0, while a positive pid means its the parent proc. So I'm honestly not entirely sure

**Comment by quique0194** [comment]
Ok this is what i learned:

 1. Celery has "subworkers", when you run `celery -A app worker` it launches 1 worker with many subworkers, the number of subworkers by default is equal to the number of cores in your processor
 2. Celery by default uses **prefork** mechanism to spawn "subworkers", which means it uses fork to create a new process for each "subworker"
 3. I was initializing my mongo db connection on the signal `@signals.worker_init.connect`, but it seems that such signal is executed on the parent process, before doing the forking.
 4. To initialize the mongo db connection AFTER the forking, i needed to use the signal `@signals.worker_process_init.connect` instead.

It looks like this:

```
@signals.worker_process_init.connect
def on_worker_process_init(**kwargs):
    DatabaseConnection()
```
