### ISSUE TITLE
Allow users to test their credentials from the setting pages

### ISSUE THREAD

**Issue by 9b** [9b/chirp#17]
When viewing settings, it would be nice to allow users to test their credentials and identify if a session token has been saved. This should eliminate some confusion when the application throws an error due to invalid credentials.

**Comment by jayjpatel9717** [comment]
Hi Brandon,

I face one problem, While creating a new alert it gives me a Server Error. Also in Account->Settings->Admin, I enter right Gmail id and password But in the terminal, it shows an Email ID or password was incorrect.

**Comment by 9b** [comment]
@jayjpatel9717 this could be due to a CAPTCHA firing. Please see https://github.com/9b/chirp/issues/15, and update the Google Alerts library. This issue will include a means to better validate your identity from within the interface. When this is closed, I will ask you to test again.

**Comment by 9b** [comment]
![test-auth](https://user-images.githubusercontent.com/505557/40759053-5310a02c-645e-11e8-8f0a-f75d7888f5a9.png)
