### ISSUE TITLE
Ability to blacklist a new source

### ISSUE THREAD

**Issue by jalewis** [9b/chirp#18]
I commonly see news sources I consider unreliable or "spammy".  I'd like to be able to blacklist or mute those sources.

**Comment by 9b** [comment]
Thanks for the idea! I am going to track this under #7. The rule engine will be able to define a number of rules and then perform a set of actions against articles that match. It makes a lot of sense here to define something like `IF <article-source> CONTAINS <spam-identifier> DO <delete>`.  If I interpreted that wrong, let me know.
