### ISSUE TITLE
Unable to add new monitors

### ISSUE THREAD

**Issue by jalewis** [9b/chirp#21]
If I add a new monitor, I get this error.  "
Sever Error

Your request resulted in an error."
This is in the logs.

ERROR __init__:server_error():56 2018-11-10 03:48:19,133| 500 triggered: Failed to create monitor: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 500 (Server Error)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>500.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The server encountered an error and could not complete your request.<p>If the problem persists, please <A HREF="http://www.google.com/support/">report</A> your problem and mention this error message and the query that caused it.  <ins>That\xe2\x80\x99s all we know.</ins>\n'

I can't tell if the issue is external to chirp, like maybe google changed something on their side.  My google-alerts library is up to date.

**Comment by 9b** [comment]
Interesting. I don't think this is related to chirp, but instead the Google Alerts. I just posted a new alert to my account to test and had no issues. Would you mind DMing me (keybase chat works) or share your alert preferences here and I can see if it's a syntax issue?
